name: Test

on:
  push:
    branches:
      - "**"   # double star for all branches including nested ones, but "*" works too
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm CLI
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.1

      - name: Setup Node.js and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
